package com.rvz.serviceeverz.enums;

public enum MappingStatus {
    PENDING_SP_APPROVAL,
    PENDING_MANAGER_APPROVAL,
    ADDITIONAL_DETAILS_REQUESTED_BY_SP,
    ADDITIONAL_DETAILS_REQUESTED_BY_MANAGER,
    MANAGER_APPROVED,
    REJECTED_BY_SP,
    REJECTED_BY_MANAGER,
    ACTIVE,
    RELEASED
}
