package com.rvz.serviceeverz.enums;
public enum NotificationType {
    MAPPING_REQUEST_RECEIVED_BY_SP,
    SP_REQUESTS_ADDITIONAL_DETAILS,
    SP_APPROVED_SENT_TO_MANAGER,
    MANAGER_REQUESTS_ADDITIONAL_DETAILS,
    MANAGER_APPROVED_NOTIFY_SP,
    MANAGER_APPROVED_NOTIFY_USER,
    MANAGER_REJECTED_NOTIFY_SP,
    MANAGER_REJECTED_NOTIFY_USER,
    SP_REJECTED_NOTIFY_USER,
    RENTAL_EXPIRY_WARNING
}